<?php

namespace Addons\AlgoExpertPlus\App\Http\Controllers\Backend;

use Addons\AlgoExpertPlus\App\Http\Controllers\Controller;
use App\Http\Controllers\Backend\ConfigurationController;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\View\View;

class CronJobController extends Controller
{
    /**
     * Display cron jobs management page
     */
    public function index(): View
    {
        // Resolve ConfigurationController with dependency injection
        $configController = app(ConfigurationController::class);
        
        // Use reflection to access protected methods
        $reflection = new \ReflectionClass(ConfigurationController::class);
        $getCronJobsMethod = $reflection->getMethod('getCronJobs');
        $getCronJobsMethod->setAccessible(true);
        $getScheduledTasksMethod = $reflection->getMethod('getScheduledTasksInfo');
        $getScheduledTasksMethod->setAccessible(true);
        
        $cronJobs = $getCronJobsMethod->invoke($configController);
        $scheduledTasks = $getScheduledTasksMethod->invoke($configController);

        // Get PHP binary path
        $phpPath = defined('PHP_BINARY') ? PHP_BINARY : (function_exists('php_ini_loaded_file') ? exec('which php') : '/usr/bin/php');
        if (empty($phpPath) || !file_exists($phpPath)) {
            $phpPath = '/usr/bin/php';
        }

        $basePath = base_path();
        $mainCronCommand = "* * * * * cd {$basePath} && {$phpPath} artisan schedule:run >> /dev/null 2>&1";

        // Generate full crontab content
        $crontabContent = "# Laravel Scheduler - Required\n";
        $crontabContent .= "# This runs all scheduled tasks defined in app/Console/Kernel.php\n";
        $crontabContent .= $mainCronCommand . "\n\n";
        
        // Add other optional cron jobs
        foreach ($cronJobs as $cronJob) {
            if (isset($cronJob['command']) && !($cronJob['required'] ?? false)) {
                $crontabContent .= "# {$cronJob['title']}\n";
                $crontabContent .= "# {$cronJob['description']}\n";
                $crontabContent .= $cronJob['command'] . "\n\n";
            }
        }

        $data = [
            'title' => 'Cron Jobs Management',
            'cronJobs' => $cronJobs,
            'scheduledTasks' => $scheduledTasks,
            'mainCronCommand' => $mainCronCommand,
            'crontabContent' => $crontabContent,
            'phpPath' => $phpPath,
            'basePath' => $basePath,
        ];

        return view('algoexpert-plus::backend.system-tools.cron-jobs', $data);
    }

    /**
     * Generate crontab file for download
     */
    public function generateCrontab(): \Symfony\Component\HttpFoundation\BinaryFileResponse
    {
        // Resolve ConfigurationController with dependency injection
        $configController = app(ConfigurationController::class);
        
        $reflection = new \ReflectionClass(ConfigurationController::class);
        $getCronJobsMethod = $reflection->getMethod('getCronJobs');
        $getCronJobsMethod->setAccessible(true);
        
        $cronJobs = $getCronJobsMethod->invoke($configController);

        $phpPath = defined('PHP_BINARY') ? PHP_BINARY : '/usr/bin/php';
        $basePath = base_path();
        $mainCronCommand = "* * * * * cd {$basePath} && {$phpPath} artisan schedule:run >> /dev/null 2>&1";

        $crontabContent = "# Laravel Scheduler - Required\n";
        $crontabContent .= "# Generated by AlgoExpert++ System Tools\n";
        $crontabContent .= "# Date: " . now()->toDateTimeString() . "\n\n";
        $crontabContent .= "# Main Scheduler (runs all scheduled tasks)\n";
        $crontabContent .= $mainCronCommand . "\n\n";

        foreach ($cronJobs as $cronJob) {
            if (isset($cronJob['command']) && !($cronJob['required'] ?? false)) {
                $crontabContent .= "# {$cronJob['title']}\n";
                $crontabContent .= "# {$cronJob['description']}\n";
                $crontabContent .= $cronJob['command'] . "\n\n";
            }
        }

        $tempFile = storage_path('app/crontab_' . time() . '.txt');
        File::put($tempFile, $crontabContent);

        return response()->download($tempFile, 'crontab.txt')->deleteFileAfterSend(true);
    }

    /**
     * Test cron job execution
     */
    public function testCron(): JsonResponse
    {
        try {
            \Artisan::call('schedule:run');
            $output = \Artisan::output();

            return response()->json([
                'success' => true,
                'message' => 'Cron test executed successfully',
                'output' => $output,
            ]);
        } catch (\Throwable $e) {
            return response()->json([
                'success' => false,
                'message' => 'Cron test failed: ' . $e->getMessage(),
            ], 500);
        }
    }
}
