[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=docker exec 1Panel-php8-mrTy php /opt/1panel/apps/openresty/openresty/www/sites/aitradepulse.com/index/main/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=notifications,default,high
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/opt/1panel/apps/openresty/openresty/www/sites/aitradepulse.com/index/main/storage/logs/worker.log
stopwaitsecs=3600

[program:metaapi-stream-worker]
process_name=%(program_name)s_%(process_num)02d
command=docker exec 1Panel-php8-mrTy php /opt/1panel/apps/openresty/openresty/www/sites/aitradepulse.com/index/main/artisan metaapi:stream-worker ce37225b-9ac2-49c2-af54-05e1a27f939c
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/opt/1panel/apps/openresty/openresty/www/sites/aitradepulse.com/index/main/storage/logs/stream-worker.log
stopwaitsecs=3600
