<?php

namespace Addons\TradingPresetAddon\Database\Seeders;

use Addons\TradingPresetAddon\App\Models\TradingPreset;
use Illuminate\Database\Seeder;

class TradingPresetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $presets = [
            // 1. Conservative Scalper
            [
                'name' => 'Conservative Scalper',
                'description' => 'Low risk, quick profits. Perfect for beginners who want to start trading safely with minimal risk per trade.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['scalping', 'conservative', 'beginner', 'low-risk'],
                'position_size_mode' => 'RISK_PERCENT',
                'fixed_lot' => null,
                'risk_per_trade_pct' => 0.5,
                'max_positions' => 1,
                'max_positions_per_symbol' => 1,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'PIPS',
                'sl_pips' => 20,
                'sl_r_multiple' => null,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => true,
                'tp1_rr' => 1.5,
                'tp1_close_pct' => 100,
                'tp2_enabled' => false,
                'tp2_rr' => null,
                'tp2_close_pct' => null,
                'tp3_enabled' => false,
                'tp3_rr' => null,
                'tp3_close_pct' => null,
                'close_remaining_at_tp3' => false,
                'be_enabled' => false,
                'be_trigger_rr' => null,
                'be_offset_pips' => null,
                'ts_enabled' => false,
                'ts_mode' => 'STEP_PIPS',
                'ts_trigger_rr' => null,
                'ts_step_pips' => null,
                'ts_atr_period' => null,
                'ts_atr_multiplier' => null,
                'ts_update_interval_sec' => null,
                'layering_enabled' => false,
                'max_layers_per_symbol' => 1,
                'layer_distance_pips' => null,
                'layer_martingale_mode' => 'NONE',
                'layer_martingale_factor' => null,
                'layer_max_total_risk_pct' => null,
                'hedging_enabled' => false,
                'hedge_trigger_drawdown_pct' => null,
                'hedge_distance_pips' => null,
                'hedge_lot_factor' => null,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => '08:00',
                'trading_hours_end' => '18:00',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday (1+2+4+8+16)
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => true,
                'weekly_target_enabled' => true,
                'weekly_target_profit_pct' => 2.0,
                'weekly_reset_day' => 1, // Monday
                'auto_stop_on_weekly_target' => true,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],

            // 2. Swing Trader
            [
                'name' => 'Swing Trader',
                'description' => 'Medium-term trading strategy with multiple take profit levels. Uses break-even and trailing stop for better risk management.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['swing', 'medium-term', 'multi-tp', 'break-even'],
                'position_size_mode' => 'RISK_PERCENT',
                'fixed_lot' => null,
                'risk_per_trade_pct' => 1.0,
                'max_positions' => 3,
                'max_positions_per_symbol' => 1,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'PIPS',
                'sl_pips' => 50,
                'sl_r_multiple' => null,
                'tp_mode' => 'MULTI',
                'tp1_enabled' => true,
                'tp1_rr' => 2.0,
                'tp1_close_pct' => 30,
                'tp2_enabled' => true,
                'tp2_rr' => 3.0,
                'tp2_close_pct' => 40,
                'tp3_enabled' => true,
                'tp3_rr' => 5.0,
                'tp3_close_pct' => 30,
                'close_remaining_at_tp3' => false,
                'be_enabled' => true,
                'be_trigger_rr' => 1.5,
                'be_offset_pips' => 0,
                'ts_enabled' => true,
                'ts_mode' => 'STEP_PIPS',
                'ts_trigger_rr' => 1.5,
                'ts_step_pips' => 20,
                'ts_atr_period' => null,
                'ts_atr_multiplier' => null,
                'ts_update_interval_sec' => 60,
                'layering_enabled' => false,
                'max_layers_per_symbol' => 1,
                'layer_distance_pips' => null,
                'layer_martingale_mode' => 'NONE',
                'layer_martingale_factor' => null,
                'layer_max_total_risk_pct' => null,
                'hedging_enabled' => false,
                'hedge_trigger_drawdown_pct' => null,
                'hedge_distance_pips' => null,
                'hedge_lot_factor' => null,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => null,
                'trading_hours_end' => null,
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => false,
                'weekly_target_enabled' => false,
                'weekly_target_profit_pct' => null,
                'weekly_reset_day' => null,
                'auto_stop_on_weekly_target' => false,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],

            // 3. Aggressive Day Trader
            [
                'name' => 'Aggressive Day Trader',
                'description' => 'High risk, high reward strategy for experienced traders. Features layering and advanced trailing stop.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['aggressive', 'day-trading', 'layering', 'high-risk'],
                'position_size_mode' => 'RISK_PERCENT',
                'fixed_lot' => null,
                'risk_per_trade_pct' => 2.0,
                'max_positions' => 5,
                'max_positions_per_symbol' => 2,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'PIPS',
                'sl_pips' => 30,
                'sl_r_multiple' => null,
                'tp_mode' => 'MULTI',
                'tp1_enabled' => true,
                'tp1_rr' => 1.5,
                'tp1_close_pct' => 50,
                'tp2_enabled' => true,
                'tp2_rr' => 2.5,
                'tp2_close_pct' => 30,
                'tp3_enabled' => true,
                'tp3_rr' => 4.0,
                'tp3_close_pct' => 20,
                'close_remaining_at_tp3' => false,
                'be_enabled' => false,
                'be_trigger_rr' => null,
                'be_offset_pips' => null,
                'ts_enabled' => true,
                'ts_mode' => 'STEP_ATR',
                'ts_trigger_rr' => 1.0,
                'ts_step_pips' => null,
                'ts_atr_period' => 14,
                'ts_atr_multiplier' => 1.5,
                'ts_update_interval_sec' => 30,
                'layering_enabled' => true,
                'max_layers_per_symbol' => 3,
                'layer_distance_pips' => 20,
                'layer_martingale_mode' => 'MULTIPLY',
                'layer_martingale_factor' => 1.5,
                'layer_max_total_risk_pct' => 10.0,
                'hedging_enabled' => false,
                'hedge_trigger_drawdown_pct' => null,
                'hedge_distance_pips' => null,
                'hedge_lot_factor' => null,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => null,
                'trading_hours_end' => null,
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => false,
                'weekly_target_enabled' => true,
                'weekly_target_profit_pct' => 5.0,
                'weekly_reset_day' => 1, // Monday
                'auto_stop_on_weekly_target' => false,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],

            // 4. Safe Long-Term
            [
                'name' => 'Safe Long-Term',
                'description' => 'Very conservative strategy for long-term traders. Minimal risk with high reward potential.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['conservative', 'long-term', 'safe', 'low-risk'],
                'position_size_mode' => 'RISK_PERCENT',
                'fixed_lot' => null,
                'risk_per_trade_pct' => 0.25,
                'max_positions' => 1,
                'max_positions_per_symbol' => 1,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'PIPS',
                'sl_pips' => 100,
                'sl_r_multiple' => null,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => true,
                'tp1_rr' => 3.0,
                'tp1_close_pct' => 100,
                'tp2_enabled' => false,
                'tp2_rr' => null,
                'tp2_close_pct' => null,
                'tp3_enabled' => false,
                'tp3_rr' => null,
                'tp3_close_pct' => null,
                'close_remaining_at_tp3' => false,
                'be_enabled' => true,
                'be_trigger_rr' => 2.0,
                'be_offset_pips' => 0,
                'ts_enabled' => false,
                'ts_mode' => 'STEP_PIPS',
                'ts_trigger_rr' => null,
                'ts_step_pips' => null,
                'ts_atr_period' => null,
                'ts_atr_multiplier' => null,
                'ts_update_interval_sec' => null,
                'layering_enabled' => false,
                'max_layers_per_symbol' => 1,
                'layer_distance_pips' => null,
                'layer_martingale_mode' => 'NONE',
                'layer_martingale_factor' => null,
                'layer_max_total_risk_pct' => null,
                'hedging_enabled' => false,
                'hedge_trigger_drawdown_pct' => null,
                'hedge_distance_pips' => null,
                'hedge_lot_factor' => null,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => '08:00',
                'trading_hours_end' => '22:00',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => true,
                'weekly_target_enabled' => true,
                'weekly_target_profit_pct' => 1.0,
                'weekly_reset_day' => 1, // Monday
                'auto_stop_on_weekly_target' => true,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],

            // 5. Grid Trading
            [
                'name' => 'Grid Trading',
                'description' => 'Grid/martingale strategy with layering and hedging. Suitable for range-bound markets.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['grid', 'martingale', 'layering', 'hedging'],
                'position_size_mode' => 'FIXED',
                'fixed_lot' => 0.01,
                'risk_per_trade_pct' => null,
                'max_positions' => 5,
                'max_positions_per_symbol' => 5,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'PIPS',
                'sl_pips' => 50,
                'sl_r_multiple' => null,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => true,
                'tp1_rr' => 1.0,
                'tp1_close_pct' => 100,
                'tp2_enabled' => false,
                'tp2_rr' => null,
                'tp2_close_pct' => null,
                'tp3_enabled' => false,
                'tp3_rr' => null,
                'tp3_close_pct' => null,
                'close_remaining_at_tp3' => false,
                'be_enabled' => false,
                'be_trigger_rr' => null,
                'be_offset_pips' => null,
                'ts_enabled' => false,
                'ts_mode' => 'STEP_PIPS',
                'ts_trigger_rr' => null,
                'ts_step_pips' => null,
                'ts_atr_period' => null,
                'ts_atr_multiplier' => null,
                'ts_update_interval_sec' => null,
                'layering_enabled' => true,
                'max_layers_per_symbol' => 5,
                'layer_distance_pips' => 15,
                'layer_martingale_mode' => 'MULTIPLY',
                'layer_martingale_factor' => 2.0,
                'layer_max_total_risk_pct' => 5.0,
                'hedging_enabled' => true,
                'hedge_trigger_drawdown_pct' => 2.0,
                'hedge_distance_pips' => 20,
                'hedge_lot_factor' => 1.0,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => null,
                'trading_hours_end' => null,
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => false,
                'weekly_target_enabled' => true,
                'weekly_target_profit_pct' => 3.0,
                'weekly_reset_day' => 1, // Monday
                'auto_stop_on_weekly_target' => false,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],

            // 6. Breakout Trader
            [
                'name' => 'Breakout Trader',
                'description' => 'Breakout/volatility strategy with structure-based SL and Chandelier trailing stop.',
                'symbol' => null,
                'timeframe' => null,
                'enabled' => true,
                'tags' => ['breakout', 'volatility', 'structure', 'chandelier'],
                'position_size_mode' => 'RISK_PERCENT',
                'fixed_lot' => null,
                'risk_per_trade_pct' => 1.5,
                'max_positions' => 2,
                'max_positions_per_symbol' => 1,
                'equity_dynamic_mode' => 'NONE',
                'equity_base' => null,
                'equity_step_factor' => null,
                'risk_min_pct' => null,
                'risk_max_pct' => null,
                'sl_mode' => 'STRUCTURE',
                'sl_pips' => null,
                'sl_r_multiple' => null,
                'tp_mode' => 'MULTI',
                'tp1_enabled' => true,
                'tp1_rr' => 2.0,
                'tp1_close_pct' => 40,
                'tp2_enabled' => true,
                'tp2_rr' => 4.0,
                'tp2_close_pct' => 40,
                'tp3_enabled' => true,
                'tp3_rr' => 6.0,
                'tp3_close_pct' => 20,
                'close_remaining_at_tp3' => false,
                'be_enabled' => true,
                'be_trigger_rr' => 1.0,
                'be_offset_pips' => 0,
                'ts_enabled' => true,
                'ts_mode' => 'CHANDELIER',
                'ts_trigger_rr' => 1.0,
                'ts_step_pips' => null,
                'ts_atr_period' => 22,
                'ts_atr_multiplier' => 3.0,
                'ts_update_interval_sec' => 60,
                'layering_enabled' => false,
                'max_layers_per_symbol' => 1,
                'layer_distance_pips' => null,
                'layer_martingale_mode' => 'NONE',
                'layer_martingale_factor' => null,
                'layer_max_total_risk_pct' => null,
                'hedging_enabled' => false,
                'hedge_trigger_drawdown_pct' => null,
                'hedge_distance_pips' => null,
                'hedge_lot_factor' => null,
                'auto_close_on_candle_close' => false,
                'auto_close_timeframe' => null,
                'hold_max_candles' => null,
                'trading_hours_start' => '08:00',
                'trading_hours_end' => '17:00',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31, // Monday to Friday
                'session_profile' => 'CUSTOM',
                'only_trade_in_session' => true,
                'weekly_target_enabled' => false,
                'weekly_target_profit_pct' => null,
                'weekly_reset_day' => null,
                'auto_stop_on_weekly_target' => false,
                'created_by_user_id' => null,
                'is_default_template' => true,
                'clonable' => true,
                'visibility' => 'PUBLIC_MARKETPLACE',
            ],
        ];

        foreach ($presets as $presetData) {
            // Check if preset already exists
            $existing = TradingPreset::where('name', $presetData['name'])
                ->where('is_default_template', true)
                ->first();

            if (!$existing) {
                TradingPreset::create($presetData);
                $this->command->info("Created preset: {$presetData['name']}");
            } else {
                $this->command->info("Preset already exists: {$presetData['name']}");
            }
        }

        $this->command->info('Default trading presets seeded successfully!');
    }
}

