<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TradingPresetSeeder extends Seeder
{
    public function run()
    {
        $presets = [
            [
                'name' => 'Conservative Scalper',
                'description' => 'Low risk, quick profits. Perfect for beginners who want to start trading safely with minimal risk per trade.',
                'enabled' => 1,
                'tags' => json_encode(['scalping', 'conservative', 'beginner', 'low-risk']),
                'position_size_mode' => 'RISK_PERCENT',
                'risk_per_trade_pct' => 0.50,
                'max_positions' => 1,
                'max_positions_per_symbol' => 1,
                'sl_mode' => 'PIPS',
                'sl_pips' => 20,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => 1,
                'tp1_rr' => 1.50,
                'tp1_close_pct' => 100.00,
                'be_enabled' => 0,
                'ts_enabled' => 0,
                'layering_enabled' => 0,
                'hedging_enabled' => 0,
                'weekly_target_enabled' => 1,
                'weekly_target_profit_pct' => 2.00,
                'weekly_reset_day' => 1,
                'auto_stop_on_weekly_target' => 1,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM',
                'trading_hours_start' => '08:00:00',
                'trading_hours_end' => '18:00:00'
            ],
            [
                'name' => 'Swing Trader',
                'description' => 'Medium-term trading strategy with multiple take profit levels. Uses break-even and trailing stop for better risk management.',
                'enabled' => 1,
                'tags' => json_encode(['swing', 'medium-term', 'multi-tp', 'break-even']),
                'position_size_mode' => 'RISK_PERCENT',
                'risk_per_trade_pct' => 1.00,
                'max_positions' => 3,
                'max_positions_per_symbol' => 1,
                'sl_mode' => 'PIPS',
                'sl_pips' => 50,
                'tp_mode' => 'MULTI',
                'tp1_enabled' => 1,
                'tp1_rr' => 2.00,
                'tp1_close_pct' => 30.00,
                'tp2_enabled' => 1,
                'tp2_rr' => 3.00,
                'tp2_close_pct' => 40.00,
                'tp3_enabled' => 1,
                'tp3_rr' => 5.00,
                'tp3_close_pct' => 30.00,
                'be_enabled' => 1,
                'be_trigger_rr' => 1.50,
                'be_offset_pips' => 0,
                'ts_enabled' => 1,
                'ts_mode' => 'STEP_PIPS',
                'ts_trigger_rr' => 1.50,
                'ts_step_pips' => 20,
                'ts_update_interval_sec' => 60,
                'layering_enabled' => 0,
                'hedging_enabled' => 0,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM'
            ],
            [
                'name' => 'Aggressive Day Trader',
                'description' => 'High risk, high reward strategy for experienced traders. Features layering and advanced trailing stop.',
                'enabled' => 1,
                'tags' => json_encode(['aggressive', 'day-trading', 'layering', 'high-risk']),
                'position_size_mode' => 'RISK_PERCENT',
                'risk_per_trade_pct' => 2.00,
                'max_positions' => 5,
                'max_positions_per_symbol' => 2,
                'sl_mode' => 'PIPS',
                'sl_pips' => 30,
                'tp_mode' => 'MULTI',
                'tp1_enabled' => 1,
                'tp1_rr' => 1.50,
                'tp1_close_pct' => 50.00,
                'tp2_enabled' => 1,
                'tp2_rr' => 2.50,
                'tp2_close_pct' => 30.00,
                'tp3_enabled' => 1,
                'tp3_rr' => 4.00,
                'tp3_close_pct' => 20.00,
                'be_enabled' => 0,
                'ts_enabled' => 1,
                'ts_mode' => 'STEP_ATR',
                'ts_trigger_rr' => 1.00,
                'ts_atr_period' => 14,
                'ts_atr_multiplier' => 1.50,
                'ts_update_interval_sec' => 30,
                'layering_enabled' => 1,
                'max_layers_per_symbol' => 3,
                'layer_distance_pips' => 20,
                'layer_martingale_mode' => 'MULTIPLY',
                'layer_martingale_factor' => 1.50,
                'layer_max_total_risk_pct' => 10.00,
                'hedging_enabled' => 0,
                'weekly_target_enabled' => 1,
                'weekly_target_profit_pct' => 5.00,
                'weekly_reset_day' => 1,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM'
            ],
            [
                'name' => 'Safe Long-Term',
                'description' => 'Very conservative strategy for long-term traders. Minimal risk with high reward potential.',
                'enabled' => 1,
                'tags' => json_encode(['conservative', 'long-term', 'safe', 'low-risk']),
                'position_size_mode' => 'RISK_PERCENT',
                'risk_per_trade_pct' => 0.25,
                'max_positions' => 1,
                'max_positions_per_symbol' => 1,
                'sl_mode' => 'PIPS',
                'sl_pips' => 100,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => 1,
                'tp1_rr' => 3.00,
                'tp1_close_pct' => 100.00,
                'be_enabled' => 1,
                'be_trigger_rr' => 2.00,
                'be_offset_pips' => 0,
                'ts_enabled' => 0,
                'layering_enabled' => 0,
                'hedging_enabled' => 0,
                'weekly_target_enabled' => 1,
                'weekly_target_profit_pct' => 1.00,
                'weekly_reset_day' => 1,
                'auto_stop_on_weekly_target' => 1,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM',
                'trading_hours_start' => '08:00:00',
                'trading_hours_end' => '22:00:00'
            ],
            [
                'name' => 'Grid Trading',
                'description' => 'Grid/martingale strategy with layering and hedging. Suitable for range-bound markets.',
                'enabled' => 1,
                'tags' => json_encode(['grid', 'martingale', 'layering', 'hedging']),
                'position_size_mode' => 'FIXED',
                'fixed_lot' => 0.01,
                'max_positions' => 5,
                'max_positions_per_symbol' => 5,
                'sl_mode' => 'PIPS',
                'sl_pips' => 50,
                'tp_mode' => 'SINGLE',
                'tp1_enabled' => 1,
                'tp1_rr' => 1.00,
                'tp1_close_pct' => 100.00,
                'be_enabled' => 0,
                'ts_enabled' => 0,
                'layering_enabled' => 1,
                'max_layers_per_symbol' => 5,
                'layer_distance_pips' => 15,
                'layer_martingale_mode' => 'MULTIPLY',
                'layer_martingale_factor' => 2.00,
                'layer_max_total_risk_pct' => 5.00,
                'hedging_enabled' => 1,
                'hedge_trigger_drawdown_pct' => 2.00,
                'hedge_distance_pips' => 20,
                'hedge_lot_factor' => 1.00,
                'weekly_target_enabled' => 1,
                'weekly_target_profit_pct' => 3.00,
                'weekly_reset_day' => 1,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM'
            ],
            [
                'name' => 'Breakout Trader',
                'description' => 'Breakout/volatility strategy with structure-based SL and Chandelier trailing stop.',
                'enabled' => 1,
                'tags' => json_encode(['breakout', 'volatility', 'structure', 'chandelier']),
                'position_size_mode' => 'RISK_PERCENT',
                'risk_per_trade_pct' => 1.50,
                'max_positions' => 2,
                'max_positions_per_symbol' => 1,
                'sl_mode' => 'STRUCTURE',
                'tp_mode' => 'MULTI',
                'tp1_enabled' => 1,
                'tp1_rr' => 2.00,
                'tp1_close_pct' => 40.00,
                'tp2_enabled' => 1,
                'tp2_rr' => 4.00,
                'tp2_close_pct' => 40.00,
                'tp3_enabled' => 1,
                'tp3_rr' => 6.00,
                'tp3_close_pct' => 20.00,
                'be_enabled' => 1,
                'be_trigger_rr' => 1.00,
                'be_offset_pips' => 0,
                'ts_enabled' => 1,
                'ts_mode' => 'CHANDELIER',
                'ts_trigger_rr' => 1.00,
                'ts_atr_period' => 22,
                'ts_atr_multiplier' => 3.00,
                'ts_update_interval_sec' => 60,
                'layering_enabled' => 0,
                'hedging_enabled' => 0,
                'only_trade_in_session' => 1,
                'is_default_template' => 1,
                'clonable' => 1,
                'visibility' => 'PUBLIC_MARKETPLACE',
                'trading_timezone' => 'SERVER',
                'trading_days_mask' => 31,
                'session_profile' => 'CUSTOM',
                'trading_hours_start' => '08:00:00',
                'trading_hours_end' => '17:00:00'
            ]
        ];

        foreach ($presets as $preset) {
            DB::table('trading_presets')->updateOrInsert(
                ['name' => $preset['name']],
                array_merge($preset, [
                    'created_at' => now(),
                    'updated_at' => now()
                ])
            );
        }
    }
}

