<?php

namespace Addons\MultiChannelSignalAddon\App\Adapters\Traits;

use Addons\MultiChannelSignalAddon\App\Models\ChannelSource;
use Illuminate\Support\Facades\Log;
use function Amp\Future\await;
use Revolt\EventLoop;

trait HandlesConnection
{
    /**
     * Connect to Telegram using MTProto (user account).
     *
     * @param ChannelSource $channelSource
     * @return bool
     */
    public function connect(ChannelSource $channelSource): bool
    {
        try {
            $this->channelSource = $channelSource;
            $this->config = $channelSource->config ?? [];

            // Check if MadelineProto is available
            if (!class_exists('\danog\MadelineProto\API')) {
                $this->logError("MadelineProto library not installed. Run: composer require danog/madelineproto");
                return false;
            }

            $apiId = $this->getConfig('api_id');
            $apiHash = $this->getConfig('api_hash');

            if (empty($apiId) || empty($apiHash)) {
                $this->logError("API ID and API Hash are required for MTProto");
                return false;
            }

            // Session file path (per channel source)
            // Admin channels use separate namespace
            // v8 uses .madeline extension instead of .session
            if ($channelSource->isAdminOwned()) {
                $this->sessionFile = storage_path('app/madelineproto/admin/' . $channelSource->id . '.madeline');
            } else {
                $this->sessionFile = storage_path('app/madelineproto/' . $channelSource->id . '.madeline');
            }

            // Ensure directory exists
            $sessionDir = dirname($this->sessionFile);
            if (!is_dir($sessionDir)) {
                mkdir($sessionDir, 0755, true);
            }

            // Settings for MadelineProto v8
            // v8 uses Settings\AppInfo object instead of array
            $appInfo = new \danog\MadelineProto\Settings\AppInfo();
            $appInfo->setApiId((int) $apiId);
            $appInfo->setApiHash($apiHash);
            // Let MadelineProto auto-detect app_version to avoid UPDATE_APP_TO_LOGIN errors
            // app_version is auto-generated by MadelineProto based on its own version
            
            $settings = new \danog\MadelineProto\Settings();
            $settings->setAppInfo($appInfo);
            
            // Disable internal logging, use Laravel logs
            // Use CALLABLE_LOGGER with no-op function to disable logging
            $logger = new \danog\MadelineProto\Settings\Logger();
            $logger->setType(\danog\MadelineProto\Logger::CALLABLE_LOGGER);
            $logger->setExtra(function () {}); // No-op callable
            $settings->setLogger($logger);
            
            // Initialize MadelineProto v8
            $this->madeline = new \danog\MadelineProto\API($this->sessionFile, $settings);

            // CRITICAL: Don't call start() during GET requests in web context UNLESS session exists
            // start() outputs web UI HTML which we want to prevent
            // But if session file exists, we're already authenticated and can safely start
            $shouldStart = true;
            $sessionExists = file_exists($this->sessionFile);
            
            if (PHP_SAPI !== 'cli') {
                if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] === 'GET') {
                    // For GET requests, only start if session file exists (already authenticated)
                    // This allows authenticated users to access dialogs/channels via GET
                    $shouldStart = $sessionExists;
                } elseif (empty($_POST)) {
                    // For POST requests without data, check if session exists
                    // This handles cases where $_POST might be empty but we still need to connect
                    $shouldStart = $sessionExists || !empty($_POST);
                }
            }
            
            if (!$shouldStart) {
                // Don't initialize if we can't start
                $this->connected = false;
                return false;
            }
            
            // Start MadelineProto - this initializes the connection and handles auth if needed
            // According to docs: start() must be called to initialize the connection
            // v8 methods are async, so we need to await them
            // Ensure event loop is running for async operations
            // Use output buffering to prevent web UI output
            ob_start();
            ob_start();
            try {
                if (!EventLoop::getDriver()) {
                    EventLoop::run(function () {
                        $startResult = $this->madeline->start();
                        if ($startResult instanceof \Amp\Future) {
                            await([$startResult])[0];
                        }
                    });
                } else {
                    $startResult = $this->madeline->start();
                    if ($startResult instanceof \Amp\Future) {
                        await([$startResult])[0];
                    }
                }
                
                // Check if start() output HTML (password prompt)
                $output = '';
                while (ob_get_level() > 0) {
                    $output .= ob_get_clean();
                }
                
                // If output contains password form, password is required
                if (!empty($output) && (strpos($output, 'Enter your password') !== false || 
                    strpos($output, 'password') !== false ||
                    strpos($output, 'PASSWORD_HASH_INVALID') !== false)) {
                    // Extract password hint if available
                    $hint = '';
                    if (preg_match('/Hint:\s*([^<]+)/i', $output, $matches)) {
                        $hint = trim($matches[1]);
                    }
                    
                    // Store password requirement in config
                    $config = $this->channelSource->config;
                    $config['password_required'] = true;
                    if ($hint) {
                        $config['password_hint'] = $hint;
                    }
                    $this->channelSource->update(['config' => $config]);
                    
                    // Log that we detected password requirement
                    Log::info("Password requirement detected in connect()", [
                        'channel_id' => $this->channelSource->id,
                        'hint' => $hint,
                        'output_length' => strlen($output)
                    ]);
                    
                    $this->connected = false;
                    return false; // Connection failed - password required
                }
                
                // Disable automatic update handling (v8 uses setNoop() method)
                // Must be called after start()
                $this->madeline->setNoop();
            } catch (\Exception $e) {
                // Clear output buffers on error
                $output = '';
                while (ob_get_level() > 0) {
                    $output .= ob_get_clean();
                }
                
                // Check if error is password-related
                if (strpos($e->getMessage(), 'password') !== false || 
                    strpos($output, 'password') !== false ||
                    $e instanceof \danog\MadelineProto\RPCError\SessionPasswordNeededError) {
                    $config = $this->channelSource->config;
                    $config['password_required'] = true;
                    $this->channelSource->update(['config' => $config]);
                }
                
                // If start() fails, might need authentication
                $this->logError("MadelineProto start() failed: " . $e->getMessage());
                $this->connected = false;
                return false;
            }

            // Check if logged in
            try {
                if (!EventLoop::getDriver()) {
                    EventLoop::run(function () use (&$self) {
                        $selfResult = $this->madeline->getSelf();
                        if ($selfResult instanceof \Amp\Future) {
                            $self = await([$selfResult])[0];
                        } else {
                            $self = $selfResult;
                        }
                    });
                } else {
                    $selfResult = $this->madeline->getSelf();
                    if ($selfResult instanceof \Amp\Future) {
                        $self = await([$selfResult])[0];
                    } else {
                        $self = $selfResult;
                    }
                }
                if (!$self) {
                    // Not logged in, need authentication
                    Log::warning("connect() - getSelf() returned null", [
                        'channel_id' => $this->channelSource->id,
                        'session_file' => $this->sessionFile,
                        'session_exists' => file_exists($this->sessionFile)
                    ]);
                    $this->connected = false;
                    return false;
                }
                
                // Log successful connection
                Log::info("connect() - Successfully authenticated", [
                    'channel_id' => $this->channelSource->id,
                    'user_id' => $self['id'] ?? null,
                    'username' => $self['username'] ?? null
                ]);
            } catch (\Exception $e) {
                // getSelf() might throw if not authenticated
                Log::error("connect() - Authentication check failed", [
                    'channel_id' => $this->channelSource->id,
                    'error' => $e->getMessage(),
                    'session_file' => $this->sessionFile,
                    'session_exists' => file_exists($this->sessionFile)
                ]);
                $this->logError("Not authenticated: " . $e->getMessage());
                $this->connected = false;
                return false;
            }

            $this->connected = true;
            return true;

        } catch (\Exception $e) {
            $this->logError("Failed to connect via MTProto: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Validate channel configuration.
     *
     * @param array $config
     * @return bool
     */
    public function validateConfig(array $config): bool
    {
        if (empty($config['api_id']) || empty($config['api_hash'])) {
            return false;
        }

        // Validate API ID is numeric
        if (!is_numeric($config['api_id'])) {
            return false;
        }

        return true;
    }

    /**
     * Get the adapter type.
     *
     * @return string
     */
    public function getType(): string
    {
        return 'telegram_mtproto';
    }

    /**
     * Get MadelineProto instance (for use in jobs).
     *
     * @return \danog\MadelineProto\API|null
     */
    public function getMadeline()
    {
        return $this->madeline;
    }

    /**
     * Disconnect from Telegram.
     *
     * @return void
     */
    public function disconnect(): void
    {
        if ($this->madeline) {
            try {
                $this->madeline->stop();
            } catch (\Exception $e) {
                // Ignore errors on disconnect
            }
            $this->madeline = null;
        }
        $this->connected = false;
    }
}
